### ISSUE TITLE
therubyracer への依存を削除したい

### ISSUE THREAD

**Issue by kzkn** [SonicGarden/cosuka_opsworks#12]
autoprefixer-rails が [9.0 から RubyRacer をサポートしなくなり](https://github.com/ai/autoprefixer-rails/blob/master/CHANGELOG.md#90-a-mari-usque-ad-mare)、cosuka_opsworks を使うプロジェクトで [assets:precompile が通らないなどの問題が発生](https://www.sonicgarden.world/groups/315/entries/580604)するようになりました。
therubyracer が不要ならば削除を、js ランタイムが必要なのであれば mini_racer などの代替 gem に依存するように修正できないかと思ってます。

**Comment by shunichi** [comment]
therubyracer いらなそう。 
node がインストールされてるだろうし。

**Comment by kzkn** [comment]
> node がインストールされてるだろうし。

それもそうですね。開発環境, CI, OpsWorks のどこでも node がインストールされてないってことはなさそう。

**Comment by kzkn** [comment]
除去するのはかんたんなんだけど、どう動作確認取ればいいだろう。`rails g cosuka_opsworks` が通ればいいのかな。
